version: "3.9"

services:
  oracle:
    container_name: oracle_with_init
    image: gvenzl/oracle-xe:21
    environment:
      ORACLE_DATABASE: cscs_db
      ORACLE_PASSWORD: cscs
      APP_USER: cscs
      APP_USER_PASSWORD: cscs
    ports:
      - "1522:1521"
    volumes:
      - ./init:/container-entrypoint-initdb.d
    tmpfs:
      - /opt/oracle/oradata
    restart: unless-stopped
