-- # This is needed : https://github.com/gvenzl/oci-oracle-xe/discussions/182#discussioncomment-4877259
conn cscs/cscs@localhost/cscs_db;

CREATE TABLE film (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50)
);

INSERT INTO film (name) VALUES ('film1');
INSERT INTO film (name) VALUES ('film2');

COMMIT;